var mongoose = require('mongoose');
propertySchema = mongoose.Schema({
    userIDFK:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'userMaster'
    },
    propertyName:{
        type:String
    },
    description:{
        type:String
    },
    address:{
        type:String
    },
    rent:{
        type:String
    },
    sharing:{
        type:String
    },
    genderType:{
        type:String
    },
    areaName:{
        type:String
    },
    cityName:{
        type:String
    },
    latitude:{
        type:Number
    },
    longitude:{
        type:Number
    },
    propertyTypeIDFK:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'propertyType'
    },
    aminityFeatures:{
        type:String
    },
    mealsAvailable:{
        type:[String],
        default:[]
    },
    menuPhoto:{
        type:String
    },
    menuPhotoUrls:{
        type:[String],
        default:[]
    },
    propertyImage:{
        type:String
    },
    propertyImageUrls:{
        type:[String],
        default:[]
    },
    videoUrl:{
        type:String
    },
    propertyCategory:{
        type:String,
        default:"PG"
    },
    pricingUnit:{
        type:String,
        default:"month"
    },
    dailyRate:{
        type:String
    },
    perDayCheckIn:{
        type:Boolean,
        default:false
    },
    depositAmount:{
        type:String
    },
    availableBeds:{
        type:Number,
        default:0
    },
    vacancyStatus:{
        type:String,
        default:"Available"
    },
    availableFrom:{
        type:String
    },
    sharingAvailability:{
        type:String
    },
    parkingAvailable:{
        type:Boolean,
        default:false
    },
    acAvailable:{
        type:Boolean,
        default:false
    },
    rating:{
        type:Number,
        default:4.6
    },
    approvalStatus:{
        type:String,
        enum:["Pending","Approved","Rejected"],
        default:"Pending"
    },
    isAvailable:{
        type:Boolean
    },
    addedOn:{
        type:String
    },
    isActive:{
        type:Boolean,
        default:true
    }
});
module.exports = mongoose.model('propertyMaster',propertySchema);
